[package]
name = "messaging"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.40"
eztracing = { version = "*", path = "../eztracing"}
thiserror = "1.0.44"
anyhow = "1.0.77"
