[workspace]
resolver = "2"
members = [
  "crates/ookami",
  "crates/ezwin", 
  "crates/eztracing",
]

# Enable a small amount of optimization in debug mode
[profile.dev.package."ookami"]
opt-level = 1

# Enable a small amount of optimization in debug mode
[profile.dev.package."ezwin"]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3
