[package]
name = "ookami"
version = "0.0.1"
edition = "2021"
authors = ["Gabriel Lugo <dev.gabriel.lugo@gmail.com>"]

# Enable a small amount of optimization in debug mode
[profile.dev.package."ookami"]
opt-level = 0

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
thiserror = "1.0.44"
anyhow = "1.0.77"

bytemuck = "1.13.1"
strum = { version = "0.25.0", features = ["derive"] }

glow = "0.13.0"
# glfw = { version = "0.54.0", features = ["log"] }

[dependencies.windows]
version = "0.52.0"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Direct3D_Fxc",
  "Win32_Graphics_Direct3D12",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Graphics_Gdi",
  "Win32_Security",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_System_WindowsProgramming",
  "Win32_UI_WindowsAndMessaging",
]
