[package]
name        = "foxy_renderer"
version     = "0.1.0"
edition     = "2021"
authors     = ["Gabriel Lugo <dev.gabriel.lugo@gmail.com>"]
repository  = "https://github.com/GTLugo/foxy"
license     = "MIT OR Apache-2.0"
readme      = "README.md"
description = "foxy"
keywords    = ["foxy"]
categories  = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow    = "1.0"
tracing   = "0.1"

bytemuck   = "1.13"
strum      = { version = "0.25", features = ["derive"] }
enumflags2 = "0.7"
messaging  = "1.0"

foxy_types = { version = "0.2", path = "../foxy_types" }

raw-window-handle = "0.5.2"
foxy_vulkan       = { version = "0.1", path = "../foxy_vulkan" }
