[package]
name              = "foxy_renderer"
version           = "0.1.0"
edition           = "2021"
authors           = ["Gabriel Lugo <dev.gabriel.lugo@gmail.com>"]
repository        = "https://github.com/GTLugo/foxy"
license.workspace = true
readme            = "README.md"
description       = "foxy"
keywords          = ["foxy"]
categories        = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
tracing   = "0.1"

bytemuck   = "1.13"
byteorder  = "1.5"
itertools  = "0.12"
strum      = { version = "0.26", features = ["derive"] }
enumflags2 = "0.7"

foxy_time  = { version = "1.1", path = "../../../foxy_time" }
foxy_log   = { version = "1.2", path = "../../../foxy_log" }
foxy_utils = { version = "0.3", path = "../../../foxy_utils" }

witer = { version = "0.11", path = "../../../witer", features = ["rwh_05", "egui", "clipboard"], default-features = false }

# vulkano         = "0.34"
# vulkano-shaders = "0.34"
ash           = { version = "0.38", features = ["linked"] }
gpu-allocator = { version = "0.25", git = "https://github.com/Traverse-Research/gpu-allocator/", branch = "ash-0.38" }
shaderc       = "0.8"

egui = "0.27"
