[package]
name       = "foxy_renderer"
version    = "0.1.0"
edition    = "2021"
repository = "https://github.com/GTLugo/foxy"
license    = "MIT OR Apache-2.0"
readme     = "README.md"
authors    = ["Gabriel Lugo <dev.gabriel.lugo@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing   = "0.1.40"

thiserror = "1.0.44"
anyhow    = "1.0.77"

bytemuck   = "1.13.1"
strum      = { version = "0.25.0", features = ["derive"] }
enumflags2 = "0.7.8"
messaging  = "1.0.6"

# using older version for compatibility with ash
raw-window-handle = "0.5.2"
foxy_vulkan       = { version = "*", path = "../foxy_vulkan" }
